name: python310
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - ipykernel
  - numpy>=1.22,<2.4
  - pandas>=2.0,<3.0
  - SQLAlchemy>=2.0
  - JPype1>=1.5
  - pip:
      - --no-index --find-links=/tmp/wheels datasource
      - --no-index --find-links=/tmp/wheels oss-storage-utils
