name: python39
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - ipykernel
  - numpy>=1.21,<2.3
  - pandas>=1.3,<2.4
  - SQLAlchemy>=1.4,<2.1
  - JPype1>=1.0.0
  - pip:
      - --no-index --find-links=/tmp/wheels datasource
      - --no-index --find-links=/tmp/wheels oss-storage-utils
